import "dotenv/config"
import { PrismaClient } from "../app/generated/prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

const colleges = [
  // IITs
  {
    name: "Indian Institute of Technology Bombay",
    slug: "iit-bombay",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    type: "IIT" as const,
    established: 1958,
    totalFees: 900000,
    rating: 4.9,
    naacGrade: "A++",
    description: "IIT Bombay is one of India's premier engineering institutions, consistently ranked among the top universities globally. Known for its research output, entrepreneurship culture, and distinguished alumni.",
    website: "https://www.iitb.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "Indian Institute of Technology Delhi",
    slug: "iit-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "IIT" as const,
    established: 1961,
    totalFees: 850000,
    rating: 4.8,
    naacGrade: "A++",
    description: "IIT Delhi is renowned for its academic excellence, cutting-edge research, and strong industry connections. Located in the heart of India's capital, it offers unmatched opportunities.",
    website: "https://home.iitd.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "Indian Institute of Technology Madras",
    slug: "iit-madras",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "IIT" as const,
    established: 1959,
    totalFees: 880000,
    rating: 4.9,
    naacGrade: "A++",
    description: "IIT Madras, the top-ranked engineering institution in India (NIRF 2023), is known for its lush green campus, world-class research facilities, and exceptional placement record.",
    website: "https://www.iitm.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "Indian Institute of Technology Kharagpur",
    slug: "iit-kharagpur",
    location: "Kharagpur, West Bengal",
    city: "Kharagpur",
    state: "West Bengal",
    type: "IIT" as const,
    established: 1951,
    totalFees: 820000,
    rating: 4.7,
    naacGrade: "A++",
    description: "The first IIT established in India, IIT Kharagpur is known for its vast campus, diverse course offerings, and strong alumni network spanning the globe.",
    website: "https://www.iitkgp.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "Indian Institute of Technology Kanpur",
    slug: "iit-kanpur",
    location: "Kanpur, Uttar Pradesh",
    city: "Kanpur",
    state: "Uttar Pradesh",
    type: "IIT" as const,
    established: 1959,
    totalFees: 870000,
    rating: 4.8,
    naacGrade: "A++",
    description: "IIT Kanpur is celebrated for pioneering computer science education in India and is known for its rigorous academics, innovative research, and entrepreneurial alumni.",
    website: "https://www.iitk.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  // NITs
  {
    name: "National Institute of Technology Trichy",
    slug: "nit-trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    type: "NIT" as const,
    established: 1964,
    totalFees: 520000,
    rating: 4.5,
    naacGrade: "A+",
    description: "NIT Trichy is consistently ranked as the top NIT in India. Known for its rigorous technical education, active research culture, and impressive placement records.",
    website: "https://www.nitt.edu",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "National Institute of Technology Warangal",
    slug: "nit-warangal",
    location: "Warangal, Telangana",
    city: "Warangal",
    state: "Telangana",
    type: "NIT" as const,
    established: 1959,
    totalFees: 500000,
    rating: 4.4,
    naacGrade: "A+",
    description: "NIT Warangal is one of the oldest and most prestigious NITs, known for its strong CSE and ECE programs, and excellent industry connections.",
    website: "https://www.nitw.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "National Institute of Technology Surathkal",
    slug: "nit-surathkal",
    location: "Mangalore, Karnataka",
    city: "Mangalore",
    state: "Karnataka",
    type: "NIT" as const,
    established: 1960,
    totalFees: 490000,
    rating: 4.3,
    naacGrade: "A",
    description: "NIT Surathkal (NITK) is nestled on the scenic coastline of Karnataka. It offers excellent technical programs and has a vibrant campus life.",
    website: "https://www.nitk.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "National Institute of Technology Calicut",
    slug: "nit-calicut",
    location: "Kozhikode, Kerala",
    city: "Kozhikode",
    state: "Kerala",
    type: "NIT" as const,
    established: 1961,
    totalFees: 480000,
    rating: 4.3,
    naacGrade: "A",
    description: "NIT Calicut is known for its beautiful green campus, quality technical education, and strong alumni network in the Gulf and US tech sectors.",
    website: "https://www.nitc.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "National Institute of Technology Rourkela",
    slug: "nit-rourkela",
    location: "Rourkela, Odisha",
    city: "Rourkela",
    state: "Odisha",
    type: "NIT" as const,
    established: 1961,
    totalFees: 460000,
    rating: 4.2,
    naacGrade: "A",
    description: "NIT Rourkela is one of the top technical institutes in Eastern India, known for its research infrastructure and strong core engineering programs.",
    website: "https://www.nitrkl.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  // IIITs
  {
    name: "IIIT Hyderabad",
    slug: "iiit-hyderabad",
    location: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    type: "IIIT" as const,
    established: 1998,
    totalFees: 1200000,
    rating: 4.6,
    naacGrade: "A+",
    description: "IIIT Hyderabad is globally recognized for its research in AI, NLP, and computer vision. Its dual degree program and research culture attract top talent.",
    website: "https://www.iiit.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "IIIT Allahabad",
    slug: "iiit-allahabad",
    location: "Prayagraj, Uttar Pradesh",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    type: "IIIT" as const,
    established: 1999,
    totalFees: 900000,
    rating: 4.1,
    naacGrade: "A",
    description: "IIIT Allahabad is one of the premier IIITs in India, known for IT and software engineering programs with strong placements in product-based companies.",
    website: "https://www.iiita.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  // Private Colleges
  {
    name: "BITS Pilani",
    slug: "bits-pilani",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    type: "DEEMED" as const,
    established: 1964,
    totalFees: 1800000,
    rating: 4.7,
    naacGrade: "A",
    description: "BITS Pilani is India's top private engineering institute, known for its practice school program, flexible curriculum, and outstanding alumni in tech and entrepreneurship.",
    website: "https://www.bits-pilani.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "VIT Vellore",
    slug: "vit-vellore",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "DEEMED" as const,
    established: 1984,
    totalFees: 800000,
    rating: 4.0,
    naacGrade: "A++",
    description: "VIT Vellore is one of India's largest and most popular private engineering universities, known for its excellent infrastructure and high placement numbers.",
    website: "https://www.vit.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "Manipal Institute of Technology",
    slug: "manipal-institute-of-technology",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    type: "DEEMED" as const,
    established: 1957,
    totalFees: 1600000,
    rating: 4.1,
    naacGrade: "A+",
    description: "MIT Manipal is a leading private engineering college with a cosmopolitan campus, known for its diverse student body and strong global alumni network.",
    website: "https://manipal.edu/mit",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "SRM Institute of Science and Technology",
    slug: "srm-institute",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "DEEMED" as const,
    established: 1985,
    totalFees: 700000,
    rating: 3.8,
    naacGrade: "A++",
    description: "SRM Institute is one of India's top-ranked private universities with excellent infrastructure, international collaborations, and a large placement cell.",
    website: "https://www.srmist.edu.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "Amity University Noida",
    slug: "amity-university-noida",
    location: "Noida, Uttar Pradesh",
    city: "Noida",
    state: "Uttar Pradesh",
    type: "PRIVATE" as const,
    established: 2005,
    totalFees: 1200000,
    rating: 3.7,
    naacGrade: "A+",
    description: "Amity University is one of India's leading private universities, offering a wide range of technical and management programs with strong industry linkages.",
    website: "https://www.amity.edu",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "Thapar Institute of Engineering and Technology",
    slug: "thapar-institute",
    location: "Patiala, Punjab",
    city: "Patiala",
    state: "Punjab",
    type: "DEEMED" as const,
    established: 1956,
    totalFees: 1400000,
    rating: 4.2,
    naacGrade: "A",
    description: "Thapar Institute is a well-regarded private deemed university known for its quality engineering programs, research output, and campus culture.",
    website: "https://www.thapar.edu",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "PSG College of Technology",
    slug: "psg-college-of-technology",
    location: "Coimbatore, Tamil Nadu",
    city: "Coimbatore",
    state: "Tamil Nadu",
    type: "PRIVATE" as const,
    established: 1951,
    totalFees: 400000,
    rating: 4.1,
    naacGrade: "A+",
    description: "PSG College of Technology is one of Tamil Nadu's premier engineering colleges, known for excellent faculty, industry-oriented curriculum, and strong placement record.",
    website: "https://www.psgtech.edu",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "Jadavpur University",
    slug: "jadavpur-university",
    location: "Kolkata, West Bengal",
    city: "Kolkata",
    state: "West Bengal",
    type: "STATE" as const,
    established: 1955,
    totalFees: 60000,
    rating: 4.4,
    naacGrade: "A++",
    description: "Jadavpur University is West Bengal's premier technical university, known for producing top engineers and researchers at very affordable fee structures.",
    website: "https://jadavpuruniversity.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "Delhi Technological University",
    slug: "delhi-technological-university",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "STATE" as const,
    established: 1941,
    totalFees: 90000,
    rating: 4.1,
    naacGrade: "A",
    description: "DTU (formerly DCE) is one of Delhi's top engineering colleges, located in the capital and offering excellent placement opportunities with top tech companies.",
    website: "https://dtu.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "NSUT Delhi",
    slug: "nsut-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "STATE" as const,
    established: 1983,
    totalFees: 80000,
    rating: 3.9,
    naacGrade: "A",
    description: "NSUT (formerly NSIT) is a top state university in Delhi, known for its IT and CSE programs and excellent placements in software companies.",
    website: "https://www.nsut.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "PES University",
    slug: "pes-university",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    type: "DEEMED" as const,
    established: 1988,
    totalFees: 1100000,
    rating: 4.0,
    naacGrade: "A",
    description: "PES University Bangalore is one of the fastest-growing private universities in India, strategically located in India's Silicon Valley with strong tech placements.",
    website: "https://pes.edu",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "R.V. College of Engineering",
    slug: "rv-college-of-engineering",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    type: "PRIVATE" as const,
    established: 1963,
    totalFees: 600000,
    rating: 4.1,
    naacGrade: "A+",
    description: "RVCE Bangalore is one of Karnataka's top engineering colleges, known for its industry-oriented education, strong alumni network, and Bangalore's tech ecosystem.",
    website: "https://www.rvce.edu.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "BMS College of Engineering",
    slug: "bms-college-of-engineering",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    type: "PRIVATE" as const,
    established: 1946,
    totalFees: 580000,
    rating: 4.0,
    naacGrade: "A+",
    description: "BMS College of Engineering is one of India's oldest and most respected private engineering colleges, known for quality technical education in Bangalore.",
    website: "https://www.bmsce.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "College of Engineering Pune",
    slug: "college-of-engineering-pune",
    location: "Pune, Maharashtra",
    city: "Pune",
    state: "Maharashtra",
    type: "STATE" as const,
    established: 1854,
    totalFees: 120000,
    rating: 4.3,
    naacGrade: "A+",
    description: "COEP is one of India's oldest engineering colleges, known for its historic campus, quality academics, and strong placements in Pune's IT and manufacturing sectors.",
    website: "https://www.coep.org.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "Netaji Subhas University of Technology",
    slug: "nsut-east-campus",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "STATE" as const,
    established: 2019,
    totalFees: 75000,
    rating: 3.7,
    naacGrade: "B+",
    description: "NSUT East Campus is a newer state engineering college in Delhi, offering competitive fee structures and growing placement records in Delhi's NCR tech corridor.",
    website: "https://www.nsut.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "Chandigarh University",
    slug: "chandigarh-university",
    location: "Chandigarh, Punjab",
    city: "Chandigarh",
    state: "Punjab",
    type: "PRIVATE" as const,
    established: 2012,
    totalFees: 600000,
    rating: 3.9,
    naacGrade: "A+",
    description: "Chandigarh University is one of the fastest-growing private universities in North India, known for its modern infrastructure and large placement drives.",
    website: "https://www.cuchd.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "Vellore Institute of Technology Chennai",
    slug: "vit-chennai",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "DEEMED" as const,
    established: 2010,
    totalFees: 750000,
    rating: 3.8,
    naacGrade: "A++",
    description: "VIT Chennai campus offers VIT's quality education in the heart of Tamil Nadu's capital, with direct access to Chennai's thriving IT industry.",
    website: "https://chennai.vit.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "Kalinga Institute of Industrial Technology",
    slug: "kiit-bhubaneswar",
    location: "Bhubaneswar, Odisha",
    city: "Bhubaneswar",
    state: "Odisha",
    type: "DEEMED" as const,
    established: 1992,
    totalFees: 1000000,
    rating: 3.9,
    naacGrade: "A+",
    description: "KIIT University in Bhubaneswar is a rapidly growing deemed university known for its massive campus, diverse programs, and active placement cell.",
    website: "https://kiit.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  // IITs (new)
  {
    name: "Indian Institute of Technology Roorkee",
    slug: "iit-roorkee",
    location: "Roorkee, Uttarakhand",
    city: "Roorkee",
    state: "Uttarakhand",
    type: "IIT" as const,
    established: 1847,
    totalFees: 860000,
    rating: 4.7,
    naacGrade: "A++",
    description: "IIT Roorkee is one of the oldest and most prestigious technical institutions in Asia. Its civil and hydro engineering programs are among the best in the world.",
    website: "https://www.iitr.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "Indian Institute of Technology Guwahati",
    slug: "iit-guwahati",
    location: "Guwahati, Assam",
    city: "Guwahati",
    state: "Assam",
    type: "IIT" as const,
    established: 1994,
    totalFees: 840000,
    rating: 4.6,
    naacGrade: "A+",
    description: "IIT Guwahati is the gateway to the northeast and has rapidly grown into one of India's leading research institutions with strong programs in engineering and sciences.",
    website: "https://www.iitg.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "Indian Institute of Technology Hyderabad",
    slug: "iit-hyderabad",
    location: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    type: "IIT" as const,
    established: 2008,
    totalFees: 830000,
    rating: 4.5,
    naacGrade: "A+",
    description: "IIT Hyderabad is among the newer IITs rapidly establishing itself as a research powerhouse, with strong ties to Hyderabad's thriving tech ecosystem.",
    website: "https://www.iith.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "Indian Institute of Technology Gandhinagar",
    slug: "iit-gandhinagar",
    location: "Gandhinagar, Gujarat",
    city: "Gandhinagar",
    state: "Gujarat",
    type: "IIT" as const,
    established: 2008,
    totalFees: 820000,
    rating: 4.4,
    naacGrade: "A",
    description: "IIT Gandhinagar is known for its liberal arts infused engineering education and close connections with Gujarat's vibrant industrial ecosystem.",
    website: "https://www.iitgn.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "Indian Institute of Technology Indore",
    slug: "iit-indore",
    location: "Indore, Madhya Pradesh",
    city: "Indore",
    state: "Madhya Pradesh",
    type: "IIT" as const,
    established: 2009,
    totalFees: 810000,
    rating: 4.3,
    naacGrade: "A",
    description: "IIT Indore is a growing IIT in the heart of India, benefiting from Indore's emergence as a major business and education hub in central India.",
    website: "https://www.iiti.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  // More NITs
  {
    name: "National Institute of Technology Kurukshetra",
    slug: "nit-kurukshetra",
    location: "Kurukshetra, Haryana",
    city: "Kurukshetra",
    state: "Haryana",
    type: "NIT" as const,
    established: 1963,
    totalFees: 470000,
    rating: 4.1,
    naacGrade: "A",
    description: "NIT Kurukshetra is one of the oldest NITs in India, known for its strong engineering programs and good placements in the Delhi-NCR corridor.",
    website: "https://nitkkr.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "National Institute of Technology Patna",
    slug: "nit-patna",
    location: "Patna, Bihar",
    city: "Patna",
    state: "Bihar",
    type: "NIT" as const,
    established: 2004,
    totalFees: 445000,
    rating: 3.9,
    naacGrade: "B+",
    description: "NIT Patna serves as a beacon of technical education in Bihar, providing quality engineering education with growing placement records in product and service companies.",
    website: "https://www.nitp.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "National Institute of Technology Surat",
    slug: "nit-surat",
    location: "Surat, Gujarat",
    city: "Surat",
    state: "Gujarat",
    type: "NIT" as const,
    established: 1961,
    totalFees: 455000,
    rating: 4.0,
    naacGrade: "A",
    description: "SVNIT Surat is a well-regarded NIT in western India, known for its strong chemical engineering programs and connections to Gujarat's thriving textile and chemical industries.",
    website: "https://www.svnit.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "NIT Silchar",
    slug: "nit-silchar",
    location: "Silchar, Assam",
    city: "Silchar",
    state: "Assam",
    type: "NIT" as const,
    established: 1967,
    totalFees: 440000,
    rating: 3.8,
    naacGrade: "A",
    description: "NIT Silchar serves the northeast India region and is one of the oldest technical institutes in the area, known for strong ECE and CSE programs.",
    website: "https://www.nits.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "Maulana Azad National Institute of Technology",
    slug: "manit-bhopal",
    location: "Bhopal, Madhya Pradesh",
    city: "Bhopal",
    state: "Madhya Pradesh",
    type: "NIT" as const,
    established: 1960,
    totalFees: 450000,
    rating: 4.0,
    naacGrade: "A",
    description: "MANIT Bhopal is one of the oldest NITs in India, strategically located in Madhya Pradesh's capital and known for its diverse engineering programs.",
    website: "https://www.manit.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  // More IIITs
  {
    name: "IIIT Delhi",
    slug: "iiit-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "IIIT" as const,
    established: 2008,
    totalFees: 1400000,
    rating: 4.4,
    naacGrade: "A+",
    description: "IIIT Delhi is one of the newer IIITs rapidly building a strong reputation in CS and ECE research. Its startup culture and industry connections in Delhi are outstanding.",
    website: "https://iiitd.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "IIIT Bangalore",
    slug: "iiit-bangalore",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    type: "IIIT" as const,
    established: 1999,
    totalFees: 1600000,
    rating: 4.3,
    naacGrade: "A",
    description: "IIIT Bangalore focuses on post-graduate education and research in information technology, with strong connections to Bangalore's global tech industry.",
    website: "https://www.iiitb.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  // More private/deemed
  {
    name: "Indian Institute of Science",
    slug: "iisc-bangalore",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    type: "CENTRAL" as const,
    established: 1909,
    totalFees: 200000,
    rating: 4.9,
    naacGrade: "A++",
    description: "IISc Bangalore is India's premier research university and one of the top science and technology institutes in the world. Its Ph.D. and M.Tech programs are legendary.",
    website: "https://www.iisc.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "Anna University",
    slug: "anna-university",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "STATE" as const,
    established: 1978,
    totalFees: 100000,
    rating: 4.2,
    naacGrade: "A++",
    description: "Anna University is Tamil Nadu's premier technical university, governing hundreds of affiliated colleges across the state with strong industry connections in Chennai.",
    website: "https://www.annauniv.edu",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "Nirma University",
    slug: "nirma-university",
    location: "Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "DEEMED" as const,
    established: 1994,
    totalFees: 900000,
    rating: 4.0,
    naacGrade: "A+",
    description: "Nirma University is one of western India's top private universities, known for its engineering and management programs with strong industry placements in Ahmedabad.",
    website: "https://www.nirmauni.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "JNTU Hyderabad",
    slug: "jntu-hyderabad",
    location: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    type: "STATE" as const,
    established: 1972,
    totalFees: 150000,
    rating: 3.8,
    naacGrade: "A+",
    description: "JNTU Hyderabad is one of Telangana's largest technical universities, governing a vast network of affiliated colleges with strong placements in Hyderabad's IT corridor.",
    website: "https://www.jntuh.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "Amrita Vishwa Vidyapeetham",
    slug: "amrita-coimbatore",
    location: "Coimbatore, Tamil Nadu",
    city: "Coimbatore",
    state: "Tamil Nadu",
    type: "DEEMED" as const,
    established: 1994,
    totalFees: 950000,
    rating: 4.1,
    naacGrade: "A++",
    description: "Amrita Vishwa Vidyapeetham is one of India's top deemed universities with campuses across Kerala and Tamil Nadu, known for research excellence and spiritual values.",
    website: "https://www.amrita.edu",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
  {
    name: "BIT Mesra",
    slug: "bit-mesra",
    location: "Ranchi, Jharkhand",
    city: "Ranchi",
    state: "Jharkhand",
    type: "DEEMED" as const,
    established: 1955,
    totalFees: 1100000,
    rating: 3.9,
    naacGrade: "A",
    description: "BIT Mesra is Jharkhand's premier engineering institution, known for its scenic campus and strong alumni in core engineering and IT sectors.",
    website: "https://www.bitmesra.ac.in",
    image: "https://images.unsplash.com/photo-1595502124338-950d33e3d4c3?w=800",
  },
  {
    name: "Visvesvaraya National Institute of Technology",
    slug: "vnit-nagpur",
    location: "Nagpur, Maharashtra",
    city: "Nagpur",
    state: "Maharashtra",
    type: "NIT" as const,
    established: 1960,
    totalFees: 460000,
    rating: 4.1,
    naacGrade: "A",
    description: "VNIT Nagpur is one of Maharashtra's premier engineering institutes, strategically positioned in central India with strong placements in both tech and core engineering.",
    website: "https://www.vnit.ac.in",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
  },
  {
    name: "Dayalbagh Educational Institute",
    slug: "dei-agra",
    location: "Agra, Uttar Pradesh",
    city: "Agra",
    state: "Uttar Pradesh",
    type: "DEEMED" as const,
    established: 1981,
    totalFees: 350000,
    rating: 3.7,
    naacGrade: "A",
    description: "DEI Agra is a unique deemed university known for its self-reliant campus, strong social values, and affordable high-quality technical education in Uttar Pradesh.",
    website: "https://www.dei.ac.in",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
  },
]

const coursesByCollegeSlug: Record<string, Array<{ name: string; duration: number; fees: number; seats: number }>> = {
  "iit-bombay": [
    { name: "B.Tech CSE", duration: 4, fees: 220000, seats: 120 },
    { name: "B.Tech ECE", duration: 4, fees: 220000, seats: 80 },
    { name: "B.Tech ME", duration: 4, fees: 220000, seats: 80 },
    { name: "M.Tech", duration: 2, fees: 150000, seats: 200 },
    { name: "MBA", duration: 2, fees: 400000, seats: 60 },
  ],
  "iit-delhi": [
    { name: "B.Tech CSE", duration: 4, fees: 210000, seats: 100 },
    { name: "B.Tech ECE", duration: 4, fees: 210000, seats: 80 },
    { name: "B.Tech CE", duration: 4, fees: 210000, seats: 60 },
    { name: "M.Tech", duration: 2, fees: 140000, seats: 180 },
    { name: "MBA", duration: 2, fees: 380000, seats: 50 },
  ],
  "iit-madras": [
    { name: "B.Tech CSE", duration: 4, fees: 215000, seats: 110 },
    { name: "B.Tech ECE", duration: 4, fees: 215000, seats: 90 },
    { name: "B.Tech ME", duration: 4, fees: 215000, seats: 80 },
    { name: "B.Tech EE", duration: 4, fees: 215000, seats: 70 },
    { name: "M.Tech", duration: 2, fees: 145000, seats: 200 },
  ],
  "iit-kharagpur": [
    { name: "B.Tech CSE", duration: 4, fees: 200000, seats: 130 },
    { name: "B.Tech ECE", duration: 4, fees: 200000, seats: 100 },
    { name: "B.Tech ME", duration: 4, fees: 200000, seats: 100 },
    { name: "MBA", duration: 2, fees: 350000, seats: 80 },
    { name: "MCA", duration: 3, fees: 180000, seats: 60 },
  ],
  "iit-kanpur": [
    { name: "B.Tech CSE", duration: 4, fees: 205000, seats: 90 },
    { name: "B.Tech ECE", duration: 4, fees: 205000, seats: 80 },
    { name: "B.Tech ME", duration: 4, fees: 205000, seats: 70 },
    { name: "B.Tech EE", duration: 4, fees: 205000, seats: 70 },
    { name: "M.Tech", duration: 2, fees: 148000, seats: 150 },
  ],
}

const defaultCourses = (fees: number) => [
  { name: "B.Tech CSE", duration: 4, fees: Math.round(fees * 0.25), seats: 120 },
  { name: "B.Tech ECE", duration: 4, fees: Math.round(fees * 0.25), seats: 90 },
  { name: "B.Tech ME", duration: 4, fees: Math.round(fees * 0.22), seats: 80 },
  { name: "B.Tech IT", duration: 4, fees: Math.round(fees * 0.24), seats: 60 },
  { name: "MBA", duration: 2, fees: Math.round(fees * 0.4), seats: 60 },
]

const getPlacementStats = (slug: string, baseAvgSalary: number, baseHighestSalary: number, basePlacementRate: number) => [
  {
    year: 2022,
    avgSalary: Math.round(baseAvgSalary * 0.85),
    highestSalary: Math.round(baseHighestSalary * 0.82),
    placementRate: Math.min(100, basePlacementRate - 5),
    medianSalary: Math.round(baseAvgSalary * 0.78),
    topRecruiters: getTopRecruiters(slug),
  },
  {
    year: 2023,
    avgSalary: Math.round(baseAvgSalary * 0.93),
    highestSalary: Math.round(baseHighestSalary * 0.91),
    placementRate: Math.min(100, basePlacementRate - 2),
    medianSalary: Math.round(baseAvgSalary * 0.86),
    topRecruiters: getTopRecruiters(slug),
  },
  {
    year: 2024,
    avgSalary: baseAvgSalary,
    highestSalary: baseHighestSalary,
    placementRate: basePlacementRate,
    medianSalary: Math.round(baseAvgSalary * 0.93),
    topRecruiters: getTopRecruiters(slug),
  },
]

function getTopRecruiters(slug: string): string[] {
  const premiumRecruiters = ["Google", "Microsoft", "Amazon", "Meta", "Apple", "Goldman Sachs", "Jane Street", "Uber", "Airbnb", "LinkedIn"]
  const midTierRecruiters = ["Infosys", "TCS", "Wipro", "Cognizant", "HCL", "Tech Mahindra", "Capgemini", "Accenture", "IBM", "Oracle"]
  const financeRecruiters = ["Deutsche Bank", "Morgan Stanley", "JP Morgan", "Citibank", "HSBC", "McKinsey", "BCG", "Bain"]
  const productRecruiters = ["Flipkart", "Swiggy", "Zomato", "Razorpay", "Paytm", "CRED", "PhonePe", "Meesho", "Navi", "Dream11"]

  if (["iit-bombay", "iit-delhi", "iit-madras", "iit-kanpur"].includes(slug)) {
    return [...premiumRecruiters.slice(0, 5), ...financeRecruiters.slice(0, 3), ...productRecruiters.slice(0, 2)]
  }
  if (["iit-kharagpur", "nit-trichy", "nit-warangal", "iiit-hyderabad", "bits-pilani"].includes(slug)) {
    return [...premiumRecruiters.slice(0, 3), ...productRecruiters.slice(0, 4), ...midTierRecruiters.slice(0, 3)]
  }
  return [...productRecruiters.slice(0, 3), ...midTierRecruiters.slice(0, 5), ...premiumRecruiters.slice(0, 2)]
}

const placementBySlug: Record<string, { avgSalary: number; highestSalary: number; placementRate: number }> = {
  "iit-bombay": { avgSalary: 2200000, highestSalary: 8000000, placementRate: 95 },
  "iit-delhi": { avgSalary: 2100000, highestSalary: 7500000, placementRate: 94 },
  "iit-madras": { avgSalary: 2300000, highestSalary: 9000000, placementRate: 96 },
  "iit-kharagpur": { avgSalary: 1900000, highestSalary: 7000000, placementRate: 92 },
  "iit-kanpur": { avgSalary: 2000000, highestSalary: 7200000, placementRate: 93 },
  "nit-trichy": { avgSalary: 1200000, highestSalary: 5000000, placementRate: 91 },
  "nit-warangal": { avgSalary: 1100000, highestSalary: 4500000, placementRate: 89 },
  "nit-surathkal": { avgSalary: 1000000, highestSalary: 4200000, placementRate: 87 },
  "nit-calicut": { avgSalary: 950000, highestSalary: 4000000, placementRate: 86 },
  "nit-rourkela": { avgSalary: 900000, highestSalary: 3800000, placementRate: 85 },
  "iiit-hyderabad": { avgSalary: 1800000, highestSalary: 7000000, placementRate: 92 },
  "iiit-allahabad": { avgSalary: 1200000, highestSalary: 5000000, placementRate: 88 },
  "bits-pilani": { avgSalary: 1600000, highestSalary: 6500000, placementRate: 93 },
  "vit-vellore": { avgSalary: 700000, highestSalary: 3500000, placementRate: 82 },
  "manipal-institute-of-technology": { avgSalary: 800000, highestSalary: 3800000, placementRate: 80 },
  "srm-institute": { avgSalary: 550000, highestSalary: 2500000, placementRate: 78 },
  "amity-university-noida": { avgSalary: 500000, highestSalary: 2200000, placementRate: 75 },
  "thapar-institute": { avgSalary: 900000, highestSalary: 4000000, placementRate: 84 },
  "psg-college-of-technology": { avgSalary: 750000, highestSalary: 3200000, placementRate: 83 },
  "jadavpur-university": { avgSalary: 1000000, highestSalary: 4500000, placementRate: 88 },
  "delhi-technological-university": { avgSalary: 1100000, highestSalary: 5000000, placementRate: 89 },
  "nsut-delhi": { avgSalary: 1000000, highestSalary: 4800000, placementRate: 87 },
  "pes-university": { avgSalary: 800000, highestSalary: 4000000, placementRate: 84 },
  "rv-college-of-engineering": { avgSalary: 750000, highestSalary: 3800000, placementRate: 82 },
  "bms-college-of-engineering": { avgSalary: 720000, highestSalary: 3500000, placementRate: 80 },
  "college-of-engineering-pune": { avgSalary: 850000, highestSalary: 3800000, placementRate: 85 },
  "nsut-east-campus": { avgSalary: 600000, highestSalary: 2800000, placementRate: 76 },
  "chandigarh-university": { avgSalary: 500000, highestSalary: 2000000, placementRate: 74 },
  "vit-chennai": { avgSalary: 650000, highestSalary: 3000000, placementRate: 79 },
  "kiit-bhubaneswar": { avgSalary: 600000, highestSalary: 2800000, placementRate: 77 },
  // New colleges
  "iit-roorkee": { avgSalary: 1950000, highestSalary: 7000000, placementRate: 93 },
  "iit-guwahati": { avgSalary: 1800000, highestSalary: 6500000, placementRate: 91 },
  "iit-hyderabad": { avgSalary: 1750000, highestSalary: 6000000, placementRate: 90 },
  "iit-gandhinagar": { avgSalary: 1600000, highestSalary: 5500000, placementRate: 88 },
  "iit-indore": { avgSalary: 1500000, highestSalary: 5000000, placementRate: 87 },
  "nit-kurukshetra": { avgSalary: 850000, highestSalary: 3600000, placementRate: 84 },
  "nit-patna": { avgSalary: 700000, highestSalary: 3000000, placementRate: 79 },
  "nit-surat": { avgSalary: 800000, highestSalary: 3400000, placementRate: 83 },
  "nit-silchar": { avgSalary: 650000, highestSalary: 2800000, placementRate: 78 },
  "manit-bhopal": { avgSalary: 780000, highestSalary: 3200000, placementRate: 82 },
  "iiit-delhi": { avgSalary: 1650000, highestSalary: 6200000, placementRate: 90 },
  "iiit-bangalore": { avgSalary: 1400000, highestSalary: 5500000, placementRate: 88 },
  "iisc-bangalore": { avgSalary: 2400000, highestSalary: 9500000, placementRate: 97 },
  "anna-university": { avgSalary: 650000, highestSalary: 2800000, placementRate: 80 },
  "nirma-university": { avgSalary: 750000, highestSalary: 3200000, placementRate: 81 },
  "jntu-hyderabad": { avgSalary: 600000, highestSalary: 2500000, placementRate: 76 },
  "amrita-coimbatore": { avgSalary: 700000, highestSalary: 3000000, placementRate: 80 },
  "bit-mesra": { avgSalary: 680000, highestSalary: 2900000, placementRate: 78 },
  "vnit-nagpur": { avgSalary: 800000, highestSalary: 3500000, placementRate: 83 },
  "dei-agra": { avgSalary: 480000, highestSalary: 2000000, placementRate: 72 },
}

const reviewTemplates = [
  { rating: 5, content: "Excellent college with world-class faculty and infrastructure. Placement support is exceptional. The peer learning environment here is unmatched. Highly recommend for anyone who wants to build a strong career in tech." },
  { rating: 4, content: "Very good college overall. The academics are rigorous but rewarding. Campus life is vibrant with lots of cultural and technical fests. Placement cell works hard to bring top companies. A few administrative processes could be smoother." },
  { rating: 5, content: "Best decision of my life to come here. The quality of professors is outstanding and the research opportunities are abundant. Alumni network is incredibly helpful in job search. Infrastructure and labs are top-notch." },
  { rating: 4, content: "Great learning environment with dedicated faculty. The college has excellent industry connections. Internship opportunities are plentiful. Hostel facilities could be improved. Overall a wonderful experience." },
  { rating: 3, content: "Decent college with good academics. Some departments are stronger than others. Placement figures look good on paper but actual packages vary significantly. Campus facilities are adequate. Would recommend if you get CSE branch." },
  { rating: 5, content: "The research culture here is phenomenal. If you want to pursue higher studies abroad or build startups, this is the place. Multiple professors with international publications. Very good exposure to real-world projects." },
  { rating: 4, content: "Solid institution with good reputation. The practical exposure through projects and internships is excellent. Some courses feel outdated but most professors are knowledgeable. Alumni community is supportive." },
  { rating: 3, content: "Average experience overall. Academics are decent but the college administration can be bureaucratic. Placement support is inconsistent across departments. Infrastructure is good but the curriculum needs more industry relevance." },
  { rating: 5, content: "This college changed my life. The combination of rigorous academics, amazing peers, and great placement support prepared me perfectly for industry. The hackathons and competitions here are incredible." },
  { rating: 4, content: "Very good college overall. Faculty is knowledgeable and approachable. The curriculum keeps up with industry trends. Strong placement in tech companies. The only downside is the high competition level, which keeps everyone on their toes." },
]

const BRANCHES = [
  { name: "CSE", salaryMult: 1.0, rateDelta: 0 },
  { name: "ECE", salaryMult: 0.82, rateDelta: -3 },
  { name: "ME",  salaryMult: 0.65, rateDelta: -10 },
  { name: "CE",  salaryMult: 0.58, rateDelta: -14 },
  { name: "EE",  salaryMult: 0.72, rateDelta: -6 },
]

function getBranchStats(avgSalary: number, highestSalary: number, placementRate: number) {
  return BRANCHES.map((b) => ({
    branch: b.name,
    stats: [2022, 2023, 2024].map((year, i) => {
      const yearMult = [0.85, 0.93, 1.0][i]
      return {
        year,
        avgSalary: Math.round(avgSalary * b.salaryMult * yearMult),
        highestSalary: Math.round(highestSalary * b.salaryMult * yearMult),
        placementRate: Math.min(100, Math.max(30, Math.round((placementRate + b.rateDelta) * yearMult + (i === 2 ? 0 : -2)))),
      }
    }),
  }))
}

async function main() {
  console.log("🌱 Seeding database...")

  // Clear existing data
  await prisma.admissionDeadline.deleteMany()
  await prisma.branchPlacementStat.deleteMany()
  await prisma.review.deleteMany()
  await prisma.savedCollege.deleteMany()
  await prisma.placementStat.deleteMany()
  await prisma.course.deleteMany()
  await prisma.college.deleteMany()
  await prisma.verificationToken.deleteMany()
  await prisma.session.deleteMany()
  await prisma.account.deleteMany()
  await prisma.user.deleteMany()

  console.log("✅ Cleared existing data")

  // Create demo user
  const demoUser = await prisma.user.create({
    data: {
      name: "Arjun Sharma",
      email: "arjun@example.com",
      image: "https://api.dicebear.com/7.x/avataaars/svg?seed=arjun",
    },
  })

  console.log("✅ Created demo user")

  // Seed colleges
  for (const college of colleges) {
    const { slug } = college
    const placement = placementBySlug[slug] ?? { avgSalary: 600000, highestSalary: 2500000, placementRate: 75 }
    const courses = coursesByCollegeSlug[slug] ?? defaultCourses(college.totalFees)
    const placementStats = getPlacementStats(slug, placement.avgSalary, placement.highestSalary, placement.placementRate)

    const created = await prisma.college.create({
      data: {
        ...college,
        courses: { create: courses },
        placementStats: { create: placementStats },
      },
    })

    // Seed branch placement stats
    const branchStats = getBranchStats(placement.avgSalary, placement.highestSalary, placement.placementRate)
    for (const b of branchStats) {
      for (const stat of b.stats) {
        await prisma.branchPlacementStat.create({
          data: { collegeId: created.id, branch: b.branch, ...stat },
        })
      }
    }

    // Create 5–8 reviews per college
    const numReviews = 5 + Math.floor(Math.random() * 4)
    const shuffled = [...reviewTemplates].sort(() => Math.random() - 0.5).slice(0, numReviews)

    for (const review of shuffled) {
      await prisma.review.create({
        data: {
          userId: demoUser.id,
          collegeId: created.id,
          rating: review.rating,
          content: review.content,
        },
      })
    }

    console.log(`  ✅ Seeded ${college.name}`)
  }

  console.log("\n🎉 Database seeded successfully!")
  console.log(`   ${colleges.length} colleges`)
  console.log(`   ${colleges.length * 5} average courses`)
  console.log(`   ${colleges.length * 3} placement stats`)
  console.log(`   ${colleges.length * 15} branch placement stats`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
